Update lualint.yml

diff --git a/.github/workflows/lualint.yml b/.github/workflows/lualint.yml
--- a/.github/workflows/lualint.yml
+++ b/.github/workflows/lualint.yml
@@ -24,9 +24,14 @@ jobs:
           
           # Install luacheck using LuaRocks
           sudo luarocks install luacheck
+          
+          # Check the exit code of the installation command
+          if [ $? -ne 0 ]; then
+            echo "Failed to install luacheck"
+            exit 1
+          fi
 
       - name: Lint code
         run: |
           # Run linting command (replace with your linting command)
           luacheck .
-
